Factory/Models/DesignTimeDbContextFactory.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace Factory.Models
{
  public class FactoryContextFactory : IDesignTimeDbContextFactory<FactoryContext>
  {

    FactoryContext IDesignTimeDbContextFactory<FactoryContext>.CreateDbContext(string[] args)
    {
      IConfigurationRoot configuration = new ConfigurationBuilder()
          .SetBasePath(Directory.GetCurrentDirectory())
          .AddJsonFile("appsettings.json")
          .Build();

      var builder = new DbContextOptionsBuilder<FactoryContext>();

      builder.UseMySql(configuration["ConnectionStrings:DefaultConnection"], ServerVersion.AutoDetect(configuration["ConnectionStrings:DefaultConnection"]));

      return new FactoryContext(builder.Options);
    }
  }
}

Factory/Models/Engineer.cs
using System.Collections.Generic;

namespace Factory.Models
{
  public class Engineer
  {
    public Engineer()
    {
      this.JoinEntities = new HashSet<EngineerMachine>();
    }

    public int EngineerId { get; set; }
    public string Name { get; set; }
    public virtual ICollection<EngineerMachine> JoinEntities { get; }
  }
}

Factory/Models/EngineerMachine.cs
namespace Factory.Models
{
  public class EngineerMachine
  {
    public int EngineerMachineId { get; set; }
    public int EngineerId { get; set; }
    public int MachineId { get; set; }
    public virtual Engineer Engineer { get; set; }
    public virtual Machine Machine { get; set; }
  }
}

Factory/Models/FactoryContext.cs
using Microsoft.EntityFrameworkCore;

namespace Factory.Models
{
  public class FactoryContext : DbContext
  {
    public virtual DbSet<Machine> Machines { get; set; }
    public DbSet<Engineer> Engineers { get; set; }
    public DbSet<EngineerMachine> EngineerMachine { get; set; }
    
    public FactoryContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

Factory/Models/Machine.cs
using System.Collections.Generic;

namespace Factory.Models
{
  public class Machine
  {
    public Machine()
    {
      this.JoinEntities = new HashSet<EngineerMachine>();
    }

    public int MachineId { get; set; }

    public string Name { get; set; }
    public string Description { get; set; }
    public virtual ICollection<EngineerMachine> JoinEntities { get; set; }
  }
}

Factory/Controllers/EngineersController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Factory.Models;

namespace FactoryControllers
{
  public class EngineersController : Controller
  {
    private readonly FactoryContext _db;

    public EngineersController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Engineers.ToList());
    }
    public ActionResult Details(int id)
    {
      var thisEngineer = _db.Engineers
      .Include(engineer => engineer.JoinEntities)
      .ThenInclude(engineer => engineer.Machine)
      .FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }

    public ActionResult Create()
    {
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Name");
      return View();
    }
    [HttpPost]
    public ActionResult Create(Engineer engineer, int MachineId)
    {
      _db.Engineers.Add(engineer);
      _db.SaveChanges();
      if (MachineId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { MachineId = MachineId, EngineerId = engineer.EngineerId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Edit(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Name");
      return View(thisEngineer);
    }
    [HttpPost]
    public ActionResult Edit(Engineer engineer, int MachineId)
    {
      if (MachineId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { MachineId = MachineId, EngineerId = engineer.EngineerId });
      }
      _db.Entry(engineer).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult AddMachine(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      ViewBag.MachineId = new SelectList(_db.Machines, "MachineId", "Name");
      return View(thisEngineer);
    }
    [HttpPost]
    public ActionResult AddMachine(Engineer engineer, int MachineId)
    {
      if (MachineId != 0)
      {
        _db.EngineerMachine.Add(new EngineerMachine() { MachineId = MachineId, EngineerId = engineer.EngineerId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Delete(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      return View(thisEngineer);
    }
    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisEngineer = _db.Engineers.FirstOrDefault(engineer => engineer.EngineerId == id);
      _db.Engineers.Remove(thisEngineer);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    [HttpPost]
    public ActionResult DeleteMachine(int joinId)
    {
      var joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
      _db.EngineerMachine.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}
  

Factory/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Factory.Controllers
{
  public class HomeController : Controller
  {
    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

Factory/Controllers/MachinesController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Factory.Models;

namespace Factory.Controllers
{
  public class MachinesController : Controller
  {
    private readonly FactoryContext _db;

    public MachinesController(FactoryContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Machine> model = _db.Machines.ToList();
      return View(model);
    }
    public ActionResult Create()
    {
      ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "Name");
      return View();
    }
    [HttpPost]
    public ActionResult Create(Machine machine)
    {
      _db.Machines.Add(machine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisMachine = _db.Machines
          .Include(machine => machine.JoinEntities)
          .ThenInclude(join => join.Engineer)
          .FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    public ActionResult Edit(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost]
    public ActionResult Edit(Machine machine)
    {
      _db.Entry(machine).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      return View(thisMachine);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisMachine = _db.Machines.FirstOrDefault(machine => machine.MachineId == id);
      _db.Machines.Remove(thisMachine);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}
  

Factory/Views/Engineers/AddMachine.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer
<h2>Add a machine</h2>
<h4>Add a machine for this engineer: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.EngineerId)
  @Html.Label("Select Machine")
  @Html.DropDownList("MachineId")

  <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to list", "Index")</p>

Factory/Views/Engineers/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h4>Add a new Engineer</h4>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  @Html.Label("Select Machine")
  @Html.DropDownList("MachineId")

  <input type="submit" value="Add new engineer" class="btn btn-outline-success">
}
<p>@Html.ActionLink("Show all engineers", "Index")</p>

Factory/Views/Engineers/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />

}
@Html.ActionLink("Back to List", "Index")

Factory/Views/Engineers/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Engineer

<h2>Engineer Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

@if (@Model.JoinEntities.Count == 0)
{
  <p>This engineer does not have any machines listed</p>
}
else
{
  <h4>Machines this engineer is licensed to repair:</h4>
  <ul>
  @foreach (var join in Model.JoinEntities)
    {
      <li>@join.Machine.Name</li>
    }
  </ul>
}
<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Edit Engineer", "Edit", new { id = Model.EngineerId })</p>
<p>@Html.ActionLink("Delete Engineer", "Delete", new { id = Model.EngineerId })</p>

Factory/Views/Engineers/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;
@model List<Factory.Models.Engineer>;

<h1>ENGINEER INDEX</h1>
<hr />
@if (Model.Count == 0)
{
  <h3>No engineers have been added yet</h3>
}
else
{
  <ol>
    @foreach (Engineer engineer in Model)
    {
      <li class="blocktext">@Html.ActionLink($"{engineer.Name}", "Details", new { id = engineer.EngineerId})</li>
    }
  </ol>
}

<p>@Html.ActionLink("Add new engineer", "Create")</p>

Factory/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Welcome to Dr Sillystringz' Factory!</h1>
<p>@Html.ActionLink("See all Engineers", "Index", "Engineers")</p> <p>@Html.ActionLink("See all Machines", "Index", "Machines")</p>

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h4>Add a new machine</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  @Html.LabelFor(model => model.Description)
  @Html.TextBoxFor(model => model.Description)
  <input type="submit" value="Add new machine" />
}
<p>@Html.ActionLink("Show all machines", "Index")</p>

Factory/Views/Machines/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

Factory/Views/Machines/Details.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine;

<h2>Machine Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>
<h3>@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)</h3>
@if (@Model.JoinEntities.Count == 0)
{
  <p>This machine does not have a qualified engineer to repair it</p>
}
else
{
  <h4>Engineers qualified to repair this  machine:</h4>
  <ul>
  @foreach (var join in Model.JoinEntities)
    {
      <li>@join.Engineer.Name</li>
    }
  </ul>
}

<p>@Html.ActionLink("Back to machines", "Index")</p>
<p>@Html.ActionLink("Edit Machine", "Edit", new { id = Model.MachineId })</p>
<p>@Html.ActionLink("Delete Machine", "Delete", new { id = Model.MachineId })</p>

Factory/Views/Machines/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Edit</h2>

<h4>Edit this machine: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.MachineId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to list", "Index")</p>

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;

<h1>Machines</h1>

<hr />
@if (Model.Count == 0)
{
  <h3>No machines have been added yet</h3>
}
else
{
  <ol>
    @foreach (Machine machine in Model)
    {
      <li class="blocktext">@Html.ActionLink($"{machine.Name}", "Details", new { id = machine.MachineId})</li>
    }
  </ol>
}

<p>@Html.ActionLink("Add new machine", "Create", "Machines")</p>

Factory/Views/Shared/Footer.cshtml
<div id="footer">Dr. Sillystringz' Factory</div>

Factory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Factory!</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    <div class="container">
      @RenderBody()
      @await Html.PartialAsync("Footer")
      <br>
      <br>
      <p>@Html.ActionLink("Home", "Index", "Home")</p>
    </div>
  </body>
</html>